### ISSUE TITLE
Cannot choose folder location

### ISSUE THREAD

**Issue by Docbroke** [woefe/ShoppingList#18]
When I click settings/file location it blinks and takes me back to application main page. I am not able to change folder save path from default /data/data/.. folder. 
 I am running Android  5.1.1, with 0.9 ver of shopping list

**Comment by woefe** [comment]
Is it still a problem on v0.10.0? I was not able to reproduce the problem on v0.9.0. Can any other apps access the SD card?

**Comment by Docbroke** [comment]
No. It is solved with v0.10. Now I am able change folder save path. Thanks
