### ISSUE TITLE
Add HowTo Sync to the GitHub home page

### ISSUE THREAD

**Issue by NicolasWeb** [woefe/ShoppingList#40]
The description of this app on F-Droid says there are ways to sync with Syncthing and Nextcloud. But there is no How to. Even if we click on the link item on F-Droid
Please, add an How to on the github homepage, next to the file format.

**Comment by DJCrashdummy** [comment]
it is meant to select a folder (in the settings) to store your lists, which gets synchronized by your sync-software whichever you use.
*(synchthing and nextcloud are just two very good and free - as in beer and speech - suggestions.)*

**Comment by woefe** [comment]
I added some info to README.md and Github pages site (see 2929249)
