### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by Nuntius0** [woefe/ShoppingList#50]
Support [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) so that the app icon looks nicer on Android 8 + 9.

**Comment by Nuntius0** [comment]
I imagine the shopping trolley in the foreground layer, and the green in the background.

So if you send me an HQ version of the shopping trolley, I am happy to have a go at it :)

**Comment by woefe** [comment]
Closed in fc6e271
Thanks!
