### ISSUE TITLE
[Feature request] Add option, to rename a shopping list

### ISSUE THREAD

**Issue by ronidee** [woefe/ShoppingList#60]
An option to rename a shopping list would be good.

Is this app still being maintained? Would a pullrequest implementing this feature be merged?

**Comment by salim-b** [comment]
This seems to be a duplicate of #6

**Comment by woefe** [comment]
Closed as duplicate of #6.

PRs are welcome. I'm planning the next minor release for March. I hope I find the time to go over pending PRs by then :sweat_smile:

**Comment by ronidee** [comment]
okay good to know. unfortunately I'm in middle of exams atm, but after that I'll definitely do a PR. I use the app ~weekly and really miss that feature myself so... ^^
